spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/contracts
    username: root
    password: jwH37Q6M
    driver-class-name: org.mariadb.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog.xml
  jpa:
    show-sql: true
