spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/contracts?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&nullNamePatternMatchesAll=true&useEncoding=yes&characterEncoding=UTF-8
    username: root
    password: jwH37Q6M
  liquibase:
    change-log: classpath:/db/changelog.xml
  jpa:
    show-sql: true
