spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/contracts?createDatabaseIfNotExist=true
    username: root
    password: jwH37Q6M
  liquibase:
    change-log: classpath:/db/changelog.xml
  jpa:
    show-sql: true
